/* Central icon map so data files can reference icons by string name. */
import {
  Droplets, Thermometer, Wind, FlaskConical, Sun, Gauge, Sprout,
  ScanLine, LineChart, CloudSun, Store, Sparkles, LayoutDashboard,
  CloudRain, Cloud, Leaf, Bell, Search, Menu, X, ArrowRight, ArrowUpRight,
  TrendingUp, TrendingDown, Droplet, Activity, MapPin, Calendar, Clock,
  Check, ChevronRight, Upload, ImagePlus, RefreshCw, Send, ShoppingCart,
  Settings, LogOut, User, Eye, EyeOff, Mail, Lock, Zap, ShieldCheck,
  Waves, CircleAlert, Info, Plus, Minus, Sprout as SproutAlt,
} from 'lucide-react'

const map = {
  droplets: Droplets,
  droplet: Droplet,
  thermometer: Thermometer,
  wind: Wind,
  flask: FlaskConical,
  sun: Sun,
  gauge: Gauge,
  sprout: Sprout,
  'scan-line': ScanLine,
  'line-chart': LineChart,
  'cloud-sun': CloudSun,
  'cloud-rain': CloudRain,
  cloud: Cloud,
  store: Store,
  sparkles: Sparkles,
  'layout-dashboard': LayoutDashboard,
  leaf: Leaf,
  bell: Bell,
  search: Search,
  menu: Menu,
  x: X,
  'arrow-right': ArrowRight,
  'arrow-up-right': ArrowUpRight,
  'trending-up': TrendingUp,
  'trending-down': TrendingDown,
  activity: Activity,
  'map-pin': MapPin,
  calendar: Calendar,
  clock: Clock,
  check: Check,
  'chevron-right': ChevronRight,
  upload: Upload,
  'image-plus': ImagePlus,
  refresh: RefreshCw,
  send: Send,
  cart: ShoppingCart,
  settings: Settings,
  'log-out': LogOut,
  user: User,
  eye: Eye,
  'eye-off': EyeOff,
  mail: Mail,
  lock: Lock,
  zap: Zap,
  shield: ShieldCheck,
  waves: Waves,
  'circle-alert': CircleAlert,
  info: Info,
  plus: Plus,
  minus: Minus,
}

/** <Icon name="droplets" size={18} /> */
export default function Icon({ name, size = 18, strokeWidth = 2, className, ...rest }) {
  const Cmp = map[name] || SproutAlt
  return <Cmp size={size} strokeWidth={strokeWidth} className={className} {...rest} />
}
